
project_id = "zsptshspjdzvhgjmnjtl"

[functions.admin-2fa-send]
verify_jwt = false

[functions.admin-2fa-verify]
verify_jwt = false

[functions.bulk-import-products]
verify_jwt = true

[functions.chatbot-response]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = true

[functions.do-file-upload]
verify_jwt = false

[functions.send-2fa-email]
verify_jwt = false
