
project_id = "zsptshspjdzvhgjmnjtl"

[functions.chatbot-query]
verify_jwt = false

[functions.crawl-training-url]
verify_jwt = false

[functions.process-training-file]
verify_jwt = false

[functions.retrain-chatbot]
verify_jwt = false
